// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "ScentCraft",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

// import { Playfair_Display, Inter } from 'next/font/google'
// import { BRAND_NAME } from '@/lib/brand'
// import Navbar from '@/components/Navbar'
// import './globals.css'

// const playfair = Playfair_Display({ subsets: ['latin'], variable: '--font-display' })
// const inter = Inter({ subsets: ['latin'], variable: '--font-body' })

// export const metadata = {
//   title: BRAND_NAME,
//   description: 'Artisan fragrances, curated and custom-blended.',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={`${playfair.variable} ${inter.variable}`}>
//       <body className="bg-[#FAF8F4] text-[#1A1714] font-[family-name:var(--font-body)]">
//         <header className="bg-[#1A1714] text-white sticky top-0 z-50">
//           <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
//             <a href="/catalog" className="font-[family-name:var(--font-display)] text-xl italic">
//               {BRAND_NAME}
//             </a>
//             <nav className="hidden md:flex gap-8 text-sm">
//               <a href="/catalog" className="hover:text-[#B8924A] transition">Collections</a>
//               <a href="/customizer" className="hover:text-[#B8924A] transition">Bespoke Lab</a>
//               <a href="/orders" className="hover:text-[#B8924A] transition">Orders</a>
//             </nav>
//             <div className="flex gap-4 text-sm">
//               <button aria-label="Search">🔍</button>
//               <button aria-label="Cart">🛍️</button>
//             </div>
//           </div>
//         </header>
//         <Navbar />
//         {children}
//       </body>
//     </html>
//   )
// }


// import { Playfair_Display, Inter } from 'next/font/google'
// import { BRAND_NAME } from '@/lib/brand'
// import Navbar from '@/components/Navbar'
// import './globals.css'

// const playfair = Playfair_Display({ subsets: ['latin'], variable: '--font-display' })
// const inter = Inter({ subsets: ['latin'], variable: '--font-body' })

// export const metadata = {
//   title: BRAND_NAME,
//   description: 'Artisan fragrances, curated and custom-blended.',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={`${playfair.variable} ${inter.variable}`}>
//       <body className="bg-[#FAF8F4] text-[#1A1714] font-[family-name:var(--font-body)]">
//         <Navbar />
//         {children}
//       </body>
//     </html>
//   )
// }


// import { Playfair_Display, Inter } from 'next/font/google'
// import { BRAND_NAME } from '@/lib/brand'
// import Navbar from '@/components/Navbar'
// import './globals.css'

// const playfair = Playfair_Display({
//   subsets: ['latin'],
//   variable: '--font-display',
//   display: 'swap',
// })

// const inter = Inter({
//   subsets: ['latin'],
//   variable: '--font-body',
//   display: 'swap',
// })

// export const metadata = {
//   title: BRAND_NAME,
//   description: 'Artisan fragrances, curated and custom-blended. Lagos.',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={`${playfair.variable} ${inter.variable}`}>
//       <body className="bg-[#100E0B] text-[#F5EFE6] font-[family-name:var(--font-body)] antialiased">
//         <Navbar />
//         {children}
//       </body>
//     </html>
//   )
// }


import { Playfair_Display, Inter } from 'next/font/google'
import { BRAND_NAME } from '@/lib/brand'
import { CartProvider } from '@/lib/CartContext'
import Navbar from '@/components/Navbar'
import './globals.css'

const playfair = Playfair_Display({ 
  subsets: ['latin'], 
  variable: '--font-display', 
  display: 'swap' 
})

const inter = Inter({ 
  subsets: ['latin'], 
  variable: '--font-body', 
  display: 'swap' 
})

export const metadata = {
  title: BRAND_NAME,
  description: 'Artisan fragrances, curated and custom-blended. Lagos.',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${playfair.variable} ${inter.variable}`}>
      <body className="bg-[#100E0B] text-[#F5EFE6] font-[family-name:var(--font-body)] antialiased">
        <CartProvider>
          <Navbar />
          {children}
        </CartProvider>
      </body>
    </html>
  )
}